services:
  api:
    restart: "always"
    build:
      context: "./"
      dockerfile: "Dockerfile"
      args:
        IMAGE_REGISTRY_BASE_URL: ${IMAGE_REGISTRY_BASE_URL}
    ports:
      - "${COMINGSOON_PORT}:${COMINGSOON_PORT}"
    env_file:
      - .env
